services:
  metabase:
    image: metabase/metabase:v0.55.x
    container_name: metabase
    depends_on:
      - clickhouse
    volumes:
      - metabase-data:/metabase.db
    environment:
      - MB_DB_FILE=/metabase.db/metabase.db
    ports:
      - 3000:3000
    restart: always
    networks:
      - mongo-net

  bytebase:
    image: bytebase/bytebase:latest
    container_name: bytebase
    ports:
      - "8456:8080"
    environment:
      - BB_PORT=8080
      - BB_ADMIN_EMAIL=admin@example.com
      - BB_ADMIN_PASSWORD=your_secure_password
    volumes:
      - bytebase_data:/var/opt/bytebase
    restart: always
    networks:
      - mongo-net

volumes:
  metabase-data:
  bytebase_data:

networks:
  mongo-net:
    driver: bridge
